### ISSUE TITLE
Integrating system, environment, and dependency configuration into ESMX

### ISSUE THREAD

**Issue by danrosen25** [esmf-org/esmf#168]
### Description
Add a pre-build step for platform/system setup including calling spack to build dependencies. This level of configuration is intended to eliminate one more level of complexity in the application standup process.

### Example
```
platform:
  spack:
    compilers: path_to_compilers.yaml
    concretizer: path_to_concretizer.yaml
    config:  path_to_config.yaml
    mirrors: path_to_mirrors.yaml
    modules: path_to_modules.yaml
    packages: path_to_packages.yaml
    repos: path_to_repos.yaml
```

### Needs Discussion
- Configuring spack options from within the esmxBuild.yaml file instead of a separate file
- The configuration option key (platform, key, etc)
